"""Lab: Filesystem RAG over the GiftBot corpus.

A tiny local retriever indexes Mason Stark's family gift corpus
(./data/gift: profiles, gift_history.json, gift_ideas.json). Retrieval runs
fully offline; only the final grounded answer is generated by Azure AI Foundry.
"""
import json
import os
import re
from pathlib import Path

from dotenv import load_dotenv
from azure.identity import DefaultAzureCredential
from azure.ai.projects import AIProjectClient


def tokenize(text: str) -> set[str]:
    return set(re.findall(r"[a-zA-Z0-9]+", text.lower()))


def load_corpus(data_dir: Path) -> list[tuple[str, str]]:
    """Return (name, text) for every .md and .json doc, flattening JSON to text."""
    docs: list[tuple[str, str]] = []
    for file in sorted(data_dir.glob("*.md")):
        docs.append((file.name, file.read_text(encoding="utf-8")))
    for file in sorted(data_dir.glob("*.json")):
        docs.append((file.name, json.dumps(json.loads(file.read_text(encoding="utf-8")))))
    return docs


def retrieve_context(data_dir: Path, question: str, top_k: int = 3) -> str:
    q = tokenize(question)
    scored = [
        (len(q.intersection(tokenize(text))), name, text)
        for name, text in load_corpus(data_dir)
    ]
    scored.sort(key=lambda i: i[0], reverse=True)
    return "\n\n".join(
        f"[{name}] (score={score})\n{text[:2000]}" for score, name, text in scored[:top_k]
    )


def main() -> None:
    load_dotenv()
    endpoint = os.environ["FOUNDRY_PROJECT_ENDPOINT"]
    model = os.environ.get("FOUNDRY_MODEL_DEPLOYMENT", "gpt-4o")

    project = AIProjectClient(endpoint=endpoint, credential=DefaultAzureCredential())
    openai = project.get_openai_client()

    question = (
        "Adam Stark's birthday is coming up. Suggest 3 gift ideas that fit his "
        "likes, avoid anything he dislikes, and don't repeat a gift already in his history."
    )
    data_dir = Path(__file__).parent / "data" / "gift"
    context = retrieve_context(data_dir, question)

    prompt = (
        "You are GiftBot. Answer using ONLY the provided context. "
        "Cite the source file for each fact (e.g. per adam_profile.json). "
        "If the answer is not in context, say you do not know.\n\n"
        f"Context:\n{context}\n\nQuestion: {question}"
    )

    response = openai.responses.create(model=model, input=prompt)
    print(response.output_text)


if __name__ == "__main__":
    main()


# ──────────────────────────────────────────────────────────────────────────
# 👁  PORTAL OBSERVATION
#   Foundry portal → Agents → <agent> → Playground.
#   Ask the same question as in the script and expand "Show files used".
#   You should see the specific file chunks the agent cited.
#   Also look at the Citations / References section at the bottom of the
#   response — these link directly to the uploaded data source.
# ──────────────────────────────────────────────────────────────────────────

# ──────────────────────────────────────────────────────────────────────────
# 🏋  CHALLENGE  — Tune the vector search
#
#   FileSearchTool accepts a `max_num_results` parameter (default 10).
#   1. Change it to 3 and run the same query. Does the answer change?
#   2. Add a second query asking something NOT in the gift corpus
#      (e.g. "How do I bake sourdough?") and observe whether the agent
#      gracefully says it doesn't know or hallucinates.
#   3. BONUS: Upload one more .txt file to data/gift with a made-up gift
#      suggestion.  Re-run without restarting — does Foundry pick it up?
#      (Hint: the vector store must be re-uploaded each run as coded here.)
# ──────────────────────────────────────────────────────────────────────────
