using System.Text.RegularExpressions;
using Azure.AI.Projects;
using Azure.AI.Extensions.OpenAI;
using OpenAI.Responses;

#pragma warning disable OPENAI001

// Lab: Filesystem RAG over the GiftBot corpus.
// A tiny local retriever indexes Mason Stark's family gift corpus
// (./data/gift: profiles, gift_history.json, gift_ideas.json). Retrieval runs
// fully offline; only the final grounded answer is generated by Azure AI Foundry.

string projectEndpoint = Environment.GetEnvironmentVariable("FOUNDRY_PROJECT_ENDPOINT")
    ?? throw new InvalidOperationException("FOUNDRY_PROJECT_ENDPOINT is required.");
string modelDeployment = Environment.GetEnvironmentVariable("FOUNDRY_MODEL_DEPLOYMENT") ?? "gpt-4o";

AIProjectClient projectClient = new(
    endpoint: new Uri(projectEndpoint),
    tokenProvider: new Azure.Identity.DefaultAzureCredential());

string question =
    "Adam Stark's birthday is coming up. Suggest 3 gift ideas that fit his likes, " +
    "avoid anything he dislikes, and don't repeat a gift already in his history.";
string dataDir = Path.Combine(AppContext.BaseDirectory, "data", "gift");
string context = RetrieveContext(dataDir, question);

ProjectResponsesClient responseClient =
    projectClient.ProjectOpenAIClient.GetProjectResponsesClientForModel(modelDeployment);

ResponseResult response = await responseClient.CreateResponseAsync(
    "You are GiftBot. Answer using ONLY the provided context. " +
    "Cite the source file for each fact (e.g. per adam_profile.json). " +
    "If the answer is not in context, say you do not know.\n\n" +
    $"Context:\n{context}\n\nQuestion: {question}");

Console.WriteLine(response.GetOutputText());

// IDF-weighted keyword retrieval.
// Plain token-overlap lets generic docs (the catalog, gift history, the system
// prompt) outrank the one profile the question is actually about, because common
// words like "gift"/"likes"/"dislikes" appear everywhere. Weighting each matched
// term by its inverse document frequency makes rare, discriminating terms (like a
// person's name) dominate, so the right profile is retrieved.
static string RetrieveContext(string dataDir, string question, int topK = 5)
{
    var questionTokens = Tokenize(question);
    var corpus = new List<(string Name, string Content, HashSet<string> Tokens)>();

    foreach (string filePath in Directory.GetFiles(dataDir, "*.md").Concat(Directory.GetFiles(dataDir, "*.json")))
    {
        string content = File.ReadAllText(filePath);
        string snippet = content.Length > 2000 ? content[..2000] : content;
        corpus.Add((Path.GetFileName(filePath), snippet, Tokenize(content)));
    }

    int totalDocs = corpus.Count;
    var docFreq = new Dictionary<string, int>();
    foreach (var doc in corpus)
    {
        foreach (string token in doc.Tokens)
        {
            docFreq[token] = docFreq.GetValueOrDefault(token) + 1;
        }
    }

    var scored = corpus.Select(doc =>
    {
        double score = questionTokens.Intersect(doc.Tokens)
            .Sum(t => Math.Log((totalDocs + 1.0) / (docFreq[t] + 1.0)));
        return (Score: score, doc.Name, doc.Content);
    });

    var top = scored.OrderByDescending(x => x.Score).Take(topK);
    return string.Join("\n\n", top.Select(x => $"[{x.Name}] (score={x.Score:F2})\n{x.Content}"));
}

static HashSet<string> Tokenize(string text)
{
    return Regex.Matches(text.ToLowerInvariant(), "[a-z0-9]+")
        .Select(m => m.Value)
        .ToHashSet();
}


// ===== PORTAL OBSERVATION =====
//   Retrieval happens LOCALLY here; only the grounded prompt is sent to the
//   model (no agent, no server-side tool call), so nothing shows on the Agents
//   page. Instead watch input-token growth: the retrieved context is embedded in
//   the prompt, so input_tokens are much higher than the responses lab. See it
//   under "Models + endpoints" (classic) / "Build -> Models" (new Foundry) ->
//   your deployment -> Metrics (or Azure Monitor if App Insights is set, Lab 13).
//   For SERVER-side RAG with citations, Foundry offers a managed File Search tool
//   on agents - this lab keeps retrieval offline on purpose.
//
// ===== CHALLENGE  - Tune the retriever =====
//   The retriever returns the top 5 files (topK: 5) ranked by IDF-weighted
//   token overlap.
//   1. Change topK to 1 and re-run the same query. Does the answer get worse
//      (missing dislikes / history)? Why?
//   2. Add a SECOND question that is NOT in the gift corpus
//      (e.g. "How do I bake sourdough?") and observe whether the grounded
//      prompt makes the model say it does not know (it should, given the
//      system instruction) instead of hallucinating.
//   3. BONUS: improve RetrieveContext to also split files into ~500-char
//      chunks and score each chunk, so a long file does not dominate purely
//      because it is long.
